name: Rapid upgrade
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: emergency update from ssh
        if: github.event.issue.labels[0].name == 'upgrade'
        uses: appleboy/ssh-action@master
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          envs: TOKEN
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            docker save bennythink/yyetsbot > /root/yyetsbot-old.tar
            cd /root/YYeTsBot
            make prod
            docker-compose -f /home/WebsiteRunner/docker-compose.yml up -d
            docker-compose -f /home/BotsRunner/docker-compose.yml up -d
            curl "https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=260260121&text=Rapid%20upgrade%20complete!"
            echo "Rapid upgrade complete!"

      - name: Close Issue
        if: github.event.issue.labels[0].name == 'upgrade'
        uses: peter-evans/close-issue@v1
        with:
          comment: Upgrade complete. Close this issue.
